# fly.toml app configuration file generated for aerofinderserver-patient-pine-8491 on 2025-06-06T04:37:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aerofinderserver-patient-pine-8491'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[processes]
  app = "daphne aerofinder.asgi:application --port 8000 --bind 0.0.0.0 -v2"
  release = "python3 manage.py migrate"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
